[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=gnu++20", "-Wall", "-Wextra", "-O2"]

[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=gnu++20", "-Wall", "-Wextra", "-O2", "-D_GLIBCXX_DEBUG"]